app.module.ts수정하고 categories 폴더에 요소들 추가 했습니다
JTH011011/JTH-nest-study-eventory pull request #1
Opened 2024-10-04 07:28 UTC by JTH011011

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
category 기능을 추가하였습니다!

## Why
- 어떤 이유로 작업하셨나요?(Optional)
be를 더 잘 배우기 위한 학습 과정의 일환으로  과제를 제출합니다.

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
그 변수명이 어떤거는 단수고 어떤거는 복수여서 저도 그대로 따라했는데  무슨 기준으로 분리하신건지 궁금합니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-10-04 08:33 UTC, worjs requested changes
고생하셨습니다! 아래 하나만 반영해서 푸쉬해주세요!

**파일 및 디렉토리 이름에 categories -> category로 변경해주세요.**

기준... 음... 복수의 category를 지칭하면 categories고 한 개 혹은 도메인으로서의 category면 category를 쓰긴 합니다. strict한 기준이 있는건 아니고 한 번 고민해보시면 좋을 것 같네요!

URL이 categories라는건 어느정도 컨벤션이기도 한데, Rest API 설명하는 영상 한번 보시면 도움 될 것 같습니다.
 https://youtu.be/fB3MB8TXNXM?si=Oa3XJnS8wmkeEEOV

2024-10-05 12:57 UTC, JTH011011 commented
아 네 알겠습니다. directory 이름들이랑 파일 이름들 수정해서 제출하겠습니다!

2024-10-05 12:57 UTC, JTH011011 commented
감사합니다!

2024-10-05 16:09 UTC, worjs approved these changes
LGTM!

2024-10-07 06:17 UTC, merged