Feat/5
JTH011011/JTH-nest-study-eventory pull request #12
Opened 2024-12-07 09:32 UTC by JTH011011

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ v] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
leaveClub 제시해주신대로 짜왔습니다! 

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

Event랑 엮여있으니까 단순히 나가는 것에 비해 엮이는게 엄청 많은 것 같습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-12-07 11:11 UTC, JTH011011 commented
정말 죄송한데, 제가 feat/5 너무 복잡해서 하고 나서 아무 검증 없이 했더니, leaveClub이 관련된 event가 있을때 오류가 났습니다. 그래서 이게 그 관계된 데이터들을 모두 삭제 후에야 비로소 삭제 해야 트랜잭션이 오류 없이 되는 것을 이제서야 깨닫고, 이 부분 반영해서 leaveClub이벤트를 다시 수정해서 올립니다. (이후 떠나기는 제대로 됩니다.)

그런데 제가 feat/6을 안 만든 상태에서 deleteClub을 먼저 해놓았는데, 이걸 인지하지 못하고 그냥 푸쉬하고 pr한다음 알아버려서 이게 커밋 보기가 매우 불편하실 것 같습니다. 죄송합니다.

2024-12-08 02:16 UTC, worjs requested changes
OutClub은 Approve입니다~

2024-12-08 02:16 UTC, worjs commented on src/club/club.repository.ts
> +      .filter((event) => event.startTime > new Date())
deleteClub에서는 아직 시작안한 모임들 다 삭제한다고 했었는데,

사실 그러면 이미 시작해버린 클럽 모임들이 이 클럽을 여전히 clubId로 가지고 있어서 클럽이 삭제되지 않는 문제가 있습니다.

어제 요구사항을 제대로 구현하려면 스키마 변경을 고려해보셔야 할거예요ㅎㅎ

2024-12-08 04:31 UTC, JTH011011 commented on src/club/club.repository.ts
> +      .filter((event) => event.startTime > new Date())
넵 알겠습니다!

2024-12-08 05:07 UTC, JTH011011 commented
저 그 피드백은 반영은 했는데, 이게 repository의 createClub이나 deleteClub 말고도 추가 변경사항이 있을지 (db의 변경에 따라) 궁금ㅎ합니다. (repo 내 다른 함수들이나, 아니면 event측에서) 이것저것 생각해 봤는데 현재로써 제가 생각한 변경 필요한 함수들만 일단 commit 진행했습니다. 감사합니다!

2024-12-08 05:43 UTC, worjs requested changes
soft delete로 하기로 했다면, clubId로 club 조회하는 모든 쿼리에 deleteAt: null 조건을 추가할 필요가 있겠습니당

2024-12-08 05:43 UTC, worjs commented on src/club/club.repository.ts
> +      });
soft delete로 하셨군요
이렇게 3개는 연관관계로 한개의 메소드로 만들 수 있을거예요

data: {
  clubJoin: deleteMany
}
이런식으로 줄 수 있었던 것 같은데, 한번 해보시고 안되면 그대로 고고하시죠

2024-12-08 05:43 UTC, worjs commented on src/club/club.repository.ts
> +        deletedAt: true,
이게 필요하지는 않을 것 같은데요?

2024-12-08 06:11 UTC, JTH011011 commented on src/club/club.repository.ts
> +        deletedAt: true,
아 꼭 그 create할때 불필요한 모든 option 모든걸 다 채우지 않아도 되는군요. 생각해보니까 createdAt 같은 것도 안가져오는거 보면 그러네요. 감사합니다!

2024-12-08 06:25 UTC, JTH011011 commented on src/club/club.repository.ts
> +      });
넵 그렇게 해서 반영하겠습니다.

2024-12-08 06:26 UTC, merged