Week2assignment
JTH011011/JTH-nest-study-eventory pull request #4
Opened 2024-11-07 13:13 UTC by JTH011011

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
week2 과제입니다 (너무늦어서죄송합니다)

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
그 실수로 yarn하다가 gpt 보고 버전을 좀 바꾼 것 같은데 이부분 괜찮은지 걱정되서 이부분도 질문드리려 합니다!

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-07 14:07 UTC, worjs requested changes
고생많으셨습니다!
한방에 주셔서... 저도 빠짐없이 제대로 리뷰했나 좀 걸리긴 하는데요....ㅎㅎㅎㅎ
일단 요 코멘트들 먼저 생각해보시면 좋겠습니다~~

2024-11-07 14:07 UTC, worjs commented on src/event/event.controller.ts
> +}
`@HttpCode(204)`를 달아주면 실제로 응답으로 204를 내려주게 됩니다.
근데 ApiCreateResponse를 쓰게 되면 docs에는 201 Created라고 표시가 되어서, ApiNoContentResponse로 바꿔주면 될 것 같네요~~

2024-11-07 14:07 UTC, worjs commented on src/event/event.repository.ts
> +  }
얘도 soft delete 고려해야 하지 않을까요!

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
이거 필요할까요??

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +  }
요기도 검증 구현해주셔야합니다~~

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
db에 있는 데이터를 보았는데 정합성이 안맞을 때는 409 Conflict!

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
얘도 필요할까요?

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
얘도 원래 있던 시작 시간이랑 비교해봐야 하지 않을까요!

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +  ): Promise<EventDto> {
만약에 이미 모임에 3명 있는데 maxPeople을 2명으로 줄이는 요청이 들어오는 경우도 있을 것 같네요~

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
얘도 db를 확인해보지 않으면 모르는 에러라, 400은 아닌 것 같아요.
400은 순수하게 클라이언트의 요청 형식이 틀린 경우에만 리턴합니다.

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    }
이 검증로직이 필요할까요?

2024-11-07 14:07 UTC, worjs commented on src/event/event.service.ts
> +    const event = await this.eventRepository.getEventById(eventId);
호스트가 모임을 나가는 경우는 괜찮을까요?

2024-11-07 14:07 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  description!: string;
description은 reveiw에서만 null 가능입니다!

2024-11-07 14:07 UTC, worjs commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
얘네들도 validation 데코레이터 찾아서 넣어주세요!

2024-11-07 14:07 UTC, worjs commented on src/event/payload/patch-update-event.payload.ts
> +  endTime?: Date | null;
여기도 validator!

2024-11-07 14:07 UTC, worjs commented
버전은 크게 상관없어요~~

2024-11-09 07:32 UTC, JTH011011 commented on src/event/event.controller.ts
> +}
아 네 반영해서 수정하겠습니다!

2024-11-09 07:33 UTC, JTH011011 commented on src/event/event.repository.ts
> +  }
그 아직 이게 2주차 버전이라서 soft delete요소 추가하려 하니까 스키마랑 안맞다고 안된다고 하네요…. 일단은 다른 것 먼저 수정하고 반영하겠습니다!

2024-11-09 07:40 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
필요 없을 것 같아서 삭제 반영했습니다!

2024-11-09 07:40 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
넵 수정했습니다!

2024-11-09 07:41 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
넵. 일단은 제가 생각하기에는 둘 다 필요한 것 같아서 대체 보다는 뒤에다 추가 했습니다! 나중에 수정본 pr후 확인 부탁드립니다!

2024-11-09 07:42 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
저 검증 로직을 바꿨습니다. 에러라기 보다는, 모임에 한명이 남았을때 그사람이 나갈려고 하면은 모임이 자동 삭제가 되도록 바꾸려고 합니다

2024-11-09 15:31 UTC, JTH011011 commented on src/event/payload/create-event.payload.ts
> +  description!: string;
넵 반영했습니다!

2024-11-09 15:31 UTC, JTH011011 commented on src/event/payload/create-event.payload.ts
> +  endTime!: Date;
네 이 부분도 반영했습니다. 뒤에 꺼랑 마찬가지로 적절한 데코레이터 찾아서 넣었습니다.

2024-11-12 12:21 UTC, worjs requested changes
제출하시기 전에 예외 하나하나 직접 값 넣어가며 테스트해보시고 올려주세요
localhost:3000/docs로 접속하시면 이것저것 테스트해보실 수 있습니다~~

2024-11-12 12:21 UTC, worjs commented on src/event/event.service.ts
> +    }
호스트는 이벤트에서 나갈 수 없다는 예외처리가 나가기 함수 다음에 있는게 이상하네요
그리고 호스트가 나갈 수 없다면 0명이 될 일도 없으니 event를 그 경우에 삭제할 필요도 없구요!

2024-11-12 12:21 UTC, worjs commented on src/event/event.service.ts
> +    }
city도 있어야할듯?

2024-11-12 12:21 UTC, worjs commented on src/event/event.service.ts
> +    }
if(payload.startTime)으로 해버리면, startTime과 endTime이 모두 있는 경우에도 이곳에서 예외처리를 하게 됩니다. 의도치않게 if (payload.startTime >= event.endTime)  이 부분이 걸릴 수 있어요.

2024-11-12 12:21 UTC, worjs commented on src/event/event.service.ts
> +    }
팁을 드리면,
결국 startTime이 payload로 들어온게 있으면 온걸 쓰고 아니면 기존걸 쓰는게 됩니다.
현재 `startime = payload.startTime ??  event.startTime` 이라고 부를 수 있겠죠?
그렇게 결정된 현재의 startTime과 endTime의 정보만 가지고 정합성을 확인하면 됩니다.

2024-11-12 12:21 UTC, worjs commented on src/event/event.service.ts
> +    return EventDto.from(event);
결국 실제로 DB에 반영하는 코드는 없는 것 같습니다!

2024-11-12 12:21 UTC, worjs commented on src/event/event.repository.ts
> +  }
위에 getEvents 함수는 soft delete 처리하고 있는 것 같은데 이제 적용 하신건가요!!?

2024-11-12 12:21 UTC, worjs commented on src/event/event.repository.ts
> +  }
누군가 가입한 상태에서 event를 지우려면 먼저 가입한상태(eventJoin) 먼저 지워줘야 정상 작동할거예요

2024-11-12 12:21 UTC, worjs commented on src/event/event.repository.ts
> +  }
여기도 호스트 가입이 반영될 수 있게 변경해주세요~

2024-11-28 02:20 UTC, closed without merging