W2feedback
JTH011011/JTH-nest-study-eventory pull request #5
Opened 2024-11-09 16:05 UTC by JTH011011

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [ ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?
week2 저번에 피드백 주신거 기반으로 고쳤는데, 문제는 이게 기존 브랜치로 하려다 보니까 이리저리 오류가 나가지고, 아예 새 브랜치를 하나 더 파서 그거에다 dev로 pr하니까, 그 수정 범위가 다시 전반적으로 거대하게 되어서 feedback할때 조금 불편하실 것 같습니다. 사실 이렇게 하는 것이 제 입장에서는 최선인데, 어떻게 하면 이러한 문제가 일어나지 않을지 혹시 안다면 알려주시면 감사할 것 같습니다.
## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.

2024-11-10 01:34 UTC, worjs commented
어라 수정 범위 자체는 Event 모듈 부분이니까 이전 PR과 똑같은 것 같은데요? (문제도 딱히 없습니다)
어떤 오류들을 겪으셨는지 공유해주시면 조금 더 도움을 드릴 수 있을 것 같네요

일단 브랜치 히스토리 자체는 저쪽이랑 거의 똑같은데 거기에 추가로 피드백 반영하는 커밋이 들어간 것 같아요. 맞는지 모르겠지만ㅎㅎㅎ,,,
이전 브랜치에 다시 밀어서 그쪽 PR에서 진행하는게 좋을 것 같습니다.
아마도 수정해서 푸쉬하려니까 안되셨나? 싶기도 한데 그건 Format Code 커밋 때문일거예요.

6주차에 설명을 드릴 것 같은데, Format Code는 깃허브 액션이라고 우리가 새로운 커밋을 올릴 때 마다 특정 작업을 처리하도록 하는 기능인데요, 저는 여기다가 코드 포맷팅 기능을 집어넣어놨습니다. prittier라고 해서, 인덴트 띄어쓰기 수와 같이 코드 작성 규칙을 강제하는 라이브러리입니다. 그래서 정해진 규칙대로 작성되지 않은 코드들을 강제로 포맷하고 그렇게 변경된 사항을 Format Code 커밋으로 만들어서 추가하는겁니다.

이렇게하면 나는 분명 그 앞 커밋까지 해서 푸시를 했으니 로컬은 내 커밋까지만 있는건데, 리모트는 새로운 커밋이 하나 더 달리는 셈입니다. 그걸 다시 pull해주지 않으면 로컬과 리모트에 차이가 생기게 되고, 나중에 로컬에 추가작업을 하고 올렸을 때 충돌이 나는겁니다. 이미 이렇게 된 상황이라면 revert해서 이전 커밋으로 돌아간 뒤 pull을 하거나, 어차피 또 포맷팅 해줄거지? 하면서 force push 하는 방법도 있긴 합니다ㅎㅎㅎㅎㅎ,,,,

일단 리뷰는 이쪽에 달아드릴게요.
근데 이왕 이렇게 된거 저쪽 브랜치에서 머지를 해보면 좋겠네요.
local에서 week2 브랜치를 삭제하시고요, w2feedback에서 week2 브랜치를 하나 만들어서 포스푸시하면 될겁니다.

2024-11-10 02:26 UTC, worjs requested changes
화이팅입니다~!!

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +  async createEvent(payload: CreateEventPayload): Promise<EventDto> {
event 생성 시에 host가 가입된 상태가 되어야 해요

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    }
이 코드의 목적에 대해서 한번 고민해보시면 좋을듯.
1. put과 patch의 특성
2. @IsOptional 의 동작 방식
3. put payload와 patch payload의 차이

이런게 키워드가 될 것 같네용

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    }
둘 다 필요한가요?

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    const event = await this.eventRepository.getEventById(eventId);
얘는 카테고리 id에 0 넣고 한번 돌려보실래요?

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    }
현재 DB 상태와 차이가 있는 경우는 Conflict!
값만 놓고 봤을 때 문제가 있는 경우는 Bad Request!

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    }
기존 event의 startTime이 10월 10일이라고 치고

이때 startTime과 endTime을 전부 변경하기로 하고 각각 10월 8일, 10월 9일로 해서 요청을 보내보실래요?

기존 startTime보다 앞서 시작해서 먼저 끝나는 시간대면 아무거나 괜찮을듯

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +  }
누군가 가입한 상태에서 삭제 해보실래요?

2024-11-10 02:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
이런 경우는 findFirst라는 함수를 쓰시면 원하는 상태를 만드실 수 있을 것 같네요

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +  }
오.... 이 뭔가 예전에 카트라이더 방에서 썼던 그 방식인가요 ㅋㅋㅋ

아마 저번 리뷰에서 제가 호스트가 나간 경우를 고려해달라 해서 어쩌지 하고 이렇게 구현하신 것 같은데, 실제로 어떤 프로젝트를 개발한다고 했을 때, 이렇게 구현하는 것과 호스트는 그냥 못나가게 하는 것(제가 생각한 것)은 완전히 다른 구현입니다. 

위처럼 애매한 상황에는 기획(우리 프로젝트에서는 제가 되겠죠)쪽에 다시 물어보셔야 합니다. 제가 명세를 제대로 하지 않고 애매하게 말씀드린 탓이 더 크기는 하지만, 아무튼 무언가 명확하지 않으면 먼저 물어보는게 best라는 의미입니다ㅎㅎ

근데 이 방식도 꽤 흥미로운 것 같아서 태희님은 요렇게 해보는 것도 좋을 것 같습니다

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +    }
여기도! userId로 0 해보실래요?

2024-11-10 02:26 UTC, worjs commented on src/event/event.service.ts
> +  }
1. event update할때 그냥 repository에 있던 기존 update함수를 사용해도 될 것 같아요.
2. 모두 나가면 event를 삭제하시는 것 같은데, host가 나가는 경우의 예외처리를 고민하시다가 로직이 엉킨 느낌입니다. "모두 나간 경우"와 "host가 나간 경우"는 서로 관계가 없는 것 같습니다. 전자를 먼저 앞으로 끄집어내서 처리해버리는 게 어떨까요?
3. write 쿼리를 2개 사용할 때는 주의해야 합니다. 하나만 처리된 상태에서 불의의(?) 사고로 서버가 내려가버리면 후자는 처리되지 않으면서 정합성이 깨져버릴 수 있거든요. 무조건 전체성공 전체실패 구조로 가야 합니다.

아이디어를 살짝 드리면, leaveEvent함수의 인자로 isHost를 넘겨주는 쪽으로 구현해보시면 좋을 것 같아요. repository의 leaveEvent는 isHost가 true라면 모임에서 나가기 + 다음 userId 받아와서 hostId 변경하기 처리를 하고, false라면 모임에서 나가기 처리만 하면 되니까요.

2개 이상의 쿼리를 전체성공/전체실패로 구현하려면(transaction 구현), 요기 참고하시면 됩니다.
https://www.prisma.io/docs/orm/prisma-client/queries/transactions#transactions-overview

2024-11-10 02:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
soft delete 적용한다면 여기도 대상이 되겠군요

2024-11-10 02:26 UTC, worjs commented on src/event/event.repository.ts
> +  }
여기도 soft delete!

2024-11-10 13:54 UTC, JTH011011 commented on src/event/event.service.ts
> +  }
넵 사실.. host가 나가면 안된다는 생각을 못하고, 어릴때 게임에서 방장 나가면 자동으로 방장 바뀌는 거 생각해서 했었는데 다음부터는 애매하면 꼭 질문드리겠습니다! 이 말고도 여기에서 feedback 반영한 것들 다 그 원래 브랜치에다가 한번 해 보려고 합니다. 감사합니다!

2024-11-11 03:59 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
아 위에 if문 보면서 생각해보니 두번째 꺼는 불필요한것 같습니다. 수정하겠습니다

2024-11-11 04:00 UTC, JTH011011 commented on src/event/event.service.ts
> +    }
넵 사실 제대로 이해한건지는 모르겠는데, 일단 현재 제가 이해한 것으로는, put이면 애초에 null이 안와서 patch처럼 요소들에 대해 null check를 안해도 된다는 것으로 일단 받아들이고 수정하겠습니다.

2024-11-11 04:44 UTC, JTH011011 commented on src/event/event.repository.ts
> +  }
넵 findFirst로 간소화 했습니다. 근데 다만, eventJoin에서 soft delete(여기서 하는거 맞나요?) 하니까 빨간줄이 떠서(아까 다른 것 soft delete 말씀해주신 부분에서도 마찬가지), 일단 그 부분은 놔두고 다른것 먼저 해보겠습니다.

2024-11-11 04:53 UTC, JTH011011 commented on src/event/event.repository.ts
> +  }
그 getNumberOfParticipants? 여기서도 eventJoin 마찬가지이고.. 사실 이 기준 제가 기억나는 것으로는 schema.prisma 기준으로 알고 있는데 프리즈마 가보니까 evenJoin에는 deletedAt 항목이 없어서 그런 것인지, 아니면 제가 다른 부분에서 실수를 했는지 일단은 명확치 않아서 놔두고, 추후 수정해 보도록 하겠습니다

2024-11-11 05:09 UTC, JTH011011 commented on src/event/event.service.ts
> +  }
저 이거 요구하신 사항이 약간 헷갈리는데, 유저가 있는 상태에서 호스트가 임의로 삭제하거나 그러면 안되는건가요?

2024-11-11 07:12 UTC, JTH011011 commented on src/event/event.service.ts
> +  }
저 transaction 구현해서 하려 했는데, 제 실력으로는 계속 빨간줄이 생성되고, 또 하나 고치면 다른데서 하고 해서 일단 원래 의도하신 방법 대로 host면 못 나가도록 하는 방법으로 수정했습니다.!

2024-11-12 12:08 UTC, worjs commented on src/event/event.service.ts
> +  }
아아 그건 아닌데 지워보시면 에러가 날거라는 의미였습니다.
현재 DB구조상 eventJoin을 안지우고 event를 지우려고 하면 에러가 나거든요

2024-11-12 12:08 UTC, worjs commented on src/event/event.service.ts
> +  }
저는 코드가 안보이는데 혹시 푸쉬를 하셨나요!!?

2024-11-28 02:20 UTC, closed without merging