클럽 위한 스키마 만들기 및 기존model Event 수정
JTH011011/JTH-nest-study-eventory pull request #6
Opened 2024-11-26 18:16 UTC by JTH011011

## Type
PR 종류를 확인해 주세요.
- [ ] Refactor
- [v ] New feature
- [ ] Bug fix
- [ ] CI/CD, INFRA
- [ ] Etc

## Purpose
- 어떤 목적의 작업인가요?

승급전 과제를 위한 첫번째 작업인 schema 구성을 해 보았습니다. 리뷰 부탁드립니다!

## Why
- 어떤 이유로 작업하셨나요?(Optional)

## Additional context
- 추가로 알리고 싶으신 내용이 있으신가요?
model Club 추가
model ClubJoin 추가
model Event 수정
그리고 강의 보면서 그 auth.service.ts에서 "아 이거 잘못했다" 라고 말씀하신 한 줄 추가로 수정했습니다.

## Checklist
- Merge 나 Deploy 시 확인이 필요한 부분이 있다면 적어주세요.
과제를 하다가 뒷주차 부분을 소홀하게 하여서, 아예 올려주신 assignment 답안 코드를 기반으로 새롭게 브랜치를 파서, myAssignment을 새로운 main으로 여기고(default도 이걸로 바꿔놨습니다.), 여기에다가 말씀하셨듯이 feat/schema, feat/0, feat/1 이런 식으로 기능 별로 pr을 올릴 예정입니다. 제가 잘 이해한 것이 맞는지 확인해주시면 대단히 감사하겠습니다.

2024-11-27 00:43 UTC, worjs commented on prisma/schema.prisma
> +  role      String   @default("member")
role 컬럼은  어떤 용도인가요?

2024-11-27 00:44 UTC, worjs commented
문의주신거에 대해서는 맞는 것 같습니다 !

2024-11-27 03:58 UTC, JTH011011 commented on prisma/schema.prisma
> +  role      String   @default("member")
어 제가 이걸 고민을 좀 했었는데, event에 비해 호스트의 권한이 더 많은 것 같아서 (예를 들면 클럽 가입 신청한 리스트도 쭉 볼 수 있다와 같아) 따로 role로 "member", "host"로 나누면 어떨까 생각을 해봤는데, 지금 다시 보니까 event에서 알아서 hostID통해서 처리했던 것처럼 하면 될 것 같아서 굳이 필요 없는 부분 같습니다. 삭제하겠습니다!

2024-11-27 04:13 UTC, JTH011011 commented
그 ㅊ추가적으로 의문사항이 있는게, 여기 pr화면에서 X All checks have failed -> Continuous Integration / Cl (push) 이런 메세지가 뜨는데 혹시 무슨 뜻인지 부탁드립니다.

2024-11-27 04:33 UTC, worjs commented
아 그거는 CI라고 머지해도 문제 없는지 테스트 돌아가는건데, 지금 DB는 변경했는데 서버를 변경안해서, 서버 켜보면 에러가 많이 뜰거예요.
migration 끝나고 그것들 다 고치고 나면 pass 뜰겁니당

2024-11-27 04:33 UTC, worjs commented on prisma/schema.prisma
> +  role      String   @default("member")
아아 맞아요 만약에 role이 한 개 더 있었으면 그 접근이 맞을 것 같습니다

2024-11-27 04:34 UTC, worjs requested changes
클럽 가입 신청, 호스트의 승인/거절 등은 고려하셨을까요??

2024-11-27 04:53 UTC, JTH011011 commented
가입 신청이랑 승인/거절같은 경우에 저는 어차피 Host 있으니까 그냥 로직으로 처리하면 되지 않을까? 라고 생각했는데 이것도 미리 고려해서 db 한번 다시 수정해보겠습니다

2024-11-27 04:56 UTC, worjs commented
결국 가입 신청 중이라는 상태를 관리해야하는데 지금 구조로는 힘들지 않을까 싶었어요ㅎㅎ

2024-11-27 06:20 UTC, JTH011011 commented
넵 반영해서 다시 올렸습니다. 그런데 의문점이 하나 잇습니다. 결국에 clubApplication이 approved가 되면은 clubJoin에 추가하는건데, 이거를 clubJoin과 clubApplication이 연결되게 db상에서도 구현해야 하는지, 아니면 그냥 제가 지금 올리는 것처럼 schema 상에서는 club에만 각각 연결되게 한 뒤, Application이 approved되면 clubjoin에 유저 추가하도록 하면 되는 것일지 궁금합니다.

2024-11-27 07:46 UTC, worjs commented
> 넵 반영해서 다시 올렸습니다. 그런데 의문점이 하나 잇습니다. 결국에 clubApplication이 approved가 되면은 clubJoin에 추가하는건데, 이거를 clubJoin과 clubApplication이 연결되게 db상에서도 구현해야 하는지, 아니면 그냥 제가 지금 올리는 것처럼 schema 상에서는 club에만 각각 연결되게 한 뒤, Application이 approved되면 clubjoin에 유저 추가하도록 하면 되는 것일지 궁금합니다.

1. 오 그쵸 그러면 같은 정보가 중복이 되는거죠 ClubApplication에서는 status가 approve인 row가 있고, 동시에 clubJoin에도 있어야 하는거고, 둘 중에 하나만 있으면 정합성이 어그러진 데이터가 되는겁니다.
아니면 approve status를 없애고 clubJoin만 남길수도 있죠
이 경우는 DB 설계에서 정규화/비정규화의 장단점에 대한 논의를 찾아보시면 좋습니다.

2. rejected의 경우는 **유저가 클럽 신청하고 거절당했다는 정보가 나중에도 필요한가요?** 에 따라 넣을지 말지가 결정됩니다.
3. status를 쓰신다면 String 타입보다는 DB에서도 Enum이 있으니 그걸 적용해보시는게 좋겠습니다. 실수의 여지가 있거든요.

2024-11-27 09:10 UTC, JTH011011 commented
네 확인했습니다. 사실 제대로 말씀을 이해한 건지는 애매한 부분이 있으나, 제가 이해한 바로는 approve status가 있으면 clubJoin과의 중복 문제가 발생하고 (똑같은 일을 굳이 여러번의 단계에 걸쳐서 clubJoin에 가게 하거나, 아니면 나중에 탈퇴 할 때 approved된 club application이 남아있거나 하는 문제가 발생할 것 같아서...), 그렇기 때문에 enum을 쓰되 pending/rejected 2가지만 넣도록 하겠습니다.
일단은 정보의 필요성에 대해서 아직 확신이 없어 rejected 상태는 남겨 놓도록 하겠습니다. (사실 rejected가 필요 없으면 pending 하나라서 enum을 쓰거나 그럴 필요도 없을텐데, 문제는 status 말고 다른 방법으로 어떻게 대기시켜놓고 또 승인 / 거절을 할 지에 대해서 아이디어가 떠오르지 않습니다.)

2024-11-27 11:05 UTC, worjs commented
그쵸 그래서 이런 부분이 항상 개발하면서 불명확한 부분인데, 팀에 기획자가 있으면 물어보시면 됩니다. 개발보단 기획에 관한 내용이니까요.
"개발하면서 기획단에서 확실하지 않은 부분들은 명확하게 다시 물어봐야 한다!" 라는 부분을 생각해보셨으면 하는 마음에서 살짝 애매하게 말씀드렸습니다ㅎㅎ,,

아무튼 이번에는 거절되었다는 기록을 보관할 필요는 없습니다!
그러면 따로 status는 필요 없겠죠? clubApplication에 행이 있으면 PENDING인거고, 행이 없다면 Approve든 Reject든 결정이 된건데, Approve된 사람들은 ClubJoin에 들어가 있을테고, Reject된 데이터는 없어지면 되겠습니다~

2024-11-27 11:06 UTC, worjs approved these changes

2024-11-27 11:06 UTC, worjs commented on prisma/schema.prisma
> +  status     ApplicationStatus @default("PENDING")
얘만 날리고 머지 가시죠!

2024-11-27 11:06 UTC, worjs commented
아 Migration도 하구요

2024-11-27 16:18 UTC, JTH011011 commented on prisma/schema.prisma
> +  status     ApplicationStatus @default("PENDING")
감사합니다! 날리고 migration하고 merge하겠습니다!

2024-11-27 17:01 UTC, JTH011011 commented
@worjs 그 enum들이랑 status 날리고 migration을 하려 했는데, 예상치 못한 문제가 발생하였습니다. User의 categoryId와 관련하여, 다음 사진과 같이 기존 migration과 충돌이 뜹니다. User의 categoryId와 관련한 부분에서 충돌을 주장하는데, gpt에게 물어보니 User의 categoryId에 default값을 넣어주는 방법이나 optional로 바꾸는 등의 방법을 사용해서 NULL관련 문제를 해결하라고 하였습니다. 그러나 이번에 새롭게 만진 부분이 아니라서 함부로 제가 하지 못할 부분이라 생각하여 문의드립니다. (User는 그냥 club, clubJoin, clubApplication 부분 아래에 추가한 것 말고는 새롭게 터치한 부분이 없습니다.) 감사합니다! 
<img width="1099" alt="스크린샷 2024-11-28 오전 1 55 39" src="https://github.com/user-attachments/assets/690b435f-796f-4628-a83b-7b14ef168342">

2024-11-28 01:43 UTC, worjs commented
에러 메세지만 보면 user의 category_id의 null 값이 있다는건데, DB에 접속해서 user 데이터 중에 null로 들어가있는거 지우시거나 아무 카테고리 id 값이나 넣어보실래요

2024-11-28 02:21 UTC, merged